[build-system]
requires = ["flit_core >=3.2.0,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "installer"
authors = [
  { name = "Pradyun Gedam", email = "pradyunsg@gmail.com" },
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/pradyunsg/installer"
