name: CI
on:
  push:
  pull_request:

jobs:
  all:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Windows, Ubuntu, MacOS]

    steps:
    - uses: actions/checkout@v2

    # Get nox cache
    - name: Save date (for cache)
      id: date
      run: echo "::set-output name=date::$(date +%F)"
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nox
        key: nox-v1-${{ runner.os }}-${{ steps.date.outputs.date }}
        restore-keys: nox-v1-${{ runner.os }}

    # Get all the Python versions
    - uses: actions/setup-python@v1
      with: {python-version: pypy2}
      if: matrix.os != 'Windows'
    - uses: actions/setup-python@v1
      with: {python-version: pypy3}
      if: matrix.os != 'Windows'
    - uses: actions/setup-python@v1
      with: {python-version: 2.7}
    - uses: actions/setup-python@v1
      with: {python-version: 3.5}
    - uses: actions/setup-python@v1
      with: {python-version: 3.6}
    - uses: actions/setup-python@v1
      with: {python-version: 3.7}
    - uses: actions/setup-python@v1
      with: {python-version: 3.8}

    - run: pip install nox
    - run: nox
